language: node_js
node_js:
  - "0.10"
env:
  - NODE_ENV=travis
branches:
cache:
  directories:
    - node_modules
before_install:
 - chmod u+x *.sh
 - npm install npm@latest -g
install:
 - echo $COMMIT_MESSAGE
 - npm install
 - npm install -g gulp
 - gulp bundle
